# Generated by Django 4.2 on 2026-05-25 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-memory_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='memory',
            name='memory_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
